import type { Metadata } from 'next';
import Head from 'next/head';

import './globals.css';
import DarkModeToggle from '@/components/client/DarkModeToggle';
import HeaderBar from '@/app/HeaderBar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Head>
                <link
                    href="https://fonts.cdnfonts.com/css/star-wars"
                    rel="stylesheet"
                />
            </Head>

            <body className="text-black dark:text-white bg-white dark:bg-black transition-color duration-300 ease-in-out relative">
                <HeaderBar />
                <DarkModeToggle topRight />
                <div className="container mx-auto mt-16">{children}</div>
            </body>
        </html>
    );
}
