import type { Metadata } from "next"
import Head from "next/head"

import "./globals.css"
import DarkModeToggle from "@/components/client/DarkModeToggle"
import HeaderBar from "@/app/HeaderBar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <Head>
                <link
                    href="https://fonts.cdnfonts.com/css/star-wars"
                    rel="stylesheet"
                />
            </Head>

            <body className="relative text-black duration-300 ease-in-out bg-white dark:text-white dark:bg-black transition-color">
                <HeaderBar />
                <DarkModeToggle topRight />
                <div className="container px-2 mx-auto mt-16 md:px-0">
                    {children}
                </div>
            </body>
        </html>
    )
}
